host = "mysql-school-question"
user = "smileshark"
password = "smileshark123456"
database = "school_question_data"
# host = "mysql-school-question"
# user = "smileshark"
# password = "smileshark123456"
# database = "school_question_data"
