server:
  port: 8084
jdbc:
  host: localhost
  port: 3306
  database: school_question_data
  username: root
  password: password
mybatis:
  type-aliases-package: com.smileShark.scripts.entity
spring:
  rabbitmq:
    host: localhost # 主机名
    port: 5672 # 端口号
    virtual-host: /answer-quesiton # 虚拟主机
    username: answer-question # 用户名
    password: 123456 # 密码