spring.application.name=school-question-server
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/school_question_data?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://mysql-school-question:3306/school_question_data?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
#spring.datasource.username=smileshark
#spring.datasource.password=smileshark123456

#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://192.168.24.89:3333/school_question_data?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
#spring.datasource.username=smileshark
#spring.datasource.password=smileshark123456

#mybatis.configuration.map-underscore-to-camel-case=true
#mybatis.configuration.auto-mapping-behavior=full
#mybatis.type-aliases-package=com.smileShark.entity
#mybatis.mapper-locations=classpath:*/mapper/*.xml
#mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.type-aliases-package=com.smileShark.entity
mybatis-plus.mapper-locations=classpath:*/mapper/*.xml
mybatis.configuration.auto-mapping-behavior=full
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl


server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

logging.level.com.smileShark=DEBUG
logging.pattern.dateformat=yyyy-MM-dd HH:mm:ss.SSS
logging.file.path=./logs/${spring.application.name}

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.configUrl=/v3/api-docs/swagger-config

#CREATE USER 'smileshark'@'%' IDENTIFIED BY 'smileshark123456';
#
#GRANT ALL PRIVILEGES ON *.* TO 'smileshark'@'%' WITH GRANT OPTION;
#
#FLUSH PRIVILEGES;
#
#
#drop database if exists school_question_data;
#create database school_question_data character set utf8;
#use school_question_data;

# docker nacos ? mysql ???
#docker run --network network-nacos -d --name nacos -p 8848:8848 -p 9848:9848 -p 9849:9849 --restart=always -e MODE=standalone -e JVM_XMS=256m -e JVM_XMX=256m -v E:\nacos\mydata\nacos\logs:/home/nacos/logs -v E:\nacos\mydata\nacos\conf:/home/nacos/conf nacos/nacos-server
#
#docker run -d --name nacos-mysql --network network-nacos -e MYSQL_ROOT_PASSWORD=123456 -p 3307:3306 mysql:8