server:
  port: 8085
jdbc:
  host: localhost
  port: 3306
  username: root
  password: password
  database: answer_question_db
mybatis:
  aliases:
    package: com.smileShark.answerQuestion.entity
feign:
  sentinel:
    enabled: true
spring:
  rabbitmq:
    host: localhost # 主机名
    port: 5672 # 端口号
    virtual-host: /answer-quesiton # 虚拟主机
    username: answer-question # 用户名
    password: 123456 # 密码