version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-school-question
    ports:
      - "3333:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - /sql-file/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - smile-shark-net

  school-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-server
    ports:
      - "8080:8080"
    networks:
      - smile-shark-net

  nginx:
    image: nginx
    container_name: school-client
    ports:
      - "8888:80"
    volumes:
      - "/client/nginx.conf:/etc/nginx/nginx.conf"
      - "/client/html:/usr/share/nginx/html"
    networks:
      - smile-shark-net

networks:
  smile-shark-net:
    name: smileshark